spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  jwt:
    secret: ${JWT_SECRET}

  jackson:
    time-zone: Asia/Seoul

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_SENDER}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          writetimeout: 5000
          timeout: 5000
    mail_auth_code_expiration: 600000 # 10분

clova:
  ocr:
    url: ${CLOVA_OCR_URL}
    secret-key: ${CLOVA_SECRET_KEY}
    template-ids:
      - 36405

springdoc:
  show-login-endpoint: true

minio:
  endpoint: ${MINIO_ENDPOINT}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET}
  region: ${MINIO_REGION:us-east-1}

codef:
  public:
    key: ${PUBLIC_KEY}
  client:
    id: ${CLIENT_ID}
    secret: ${CLIENT_SECRET}
  valid:
    url: ${VALID_URL}
